// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pyryjjrniomdhtnbecrw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB5cnlqanJuaW9tZGh0bmJlY3J3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEzMDY4NzQsImV4cCI6MjA2Njg4Mjg3NH0.kgGrbDkI60MUMn0od-9YXflVoMDPYRFpaCUbMGP29K4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});